export const queryKeys = {
  authConfig: ['auth-config'] as const,
  authSessions: ['auth-sessions'] as const,
  customers: ['customers'] as const,
  drivers: ['drivers'] as const,
  vehicles: ['vehicles'] as const,
  jobs: ['jobs'] as const,
  routes: ['routes'] as const,
  optimizerHealth: ['optimizer-health'] as const,
  optimizerEvents: (limit: number) => ['optimizer-events', limit] as const,
  dispatchTimeline: (params: Record<string, string | number | undefined>) =>
    ['dispatch-timeline', params] as const,
  organizations: ['organizations'] as const,
  currentOrganization: ['current-organization'] as const,
  organizationMembers: ['organization-members'] as const,
  organizationInvitations: ['organization-invitations'] as const,
  analyticsOverview: ['analytics-overview'] as const,
  auditOverview: ['audit-overview'] as const,
  auditEntries: (params: Record<string, string | number | undefined>) =>
    ['audit-entries', params] as const,
  billingOverview: ['billing-overview'] as const,
  notificationsOverview: ['notifications-overview'] as const,
  platformOverview: ['platform-overview'] as const,
  apiKeys: ['platform-api-keys'] as const,
  webhooks: ['platform-webhooks'] as const,
  webhookDeliveries: (endpointId?: string) =>
    ['platform-webhook-deliveries', endpointId || 'all'] as const,
  driverManifest: ['driver-manifest'] as const,
  publicTracking: (token: string) => ['public-tracking', token] as const,
  trackingOverview: ['tracking-overview'] as const,
  trackingReadiness: ['tracking-readiness'] as const,
  trackingStatistics: ['tracking-statistics'] as const,
  dispatchBoard: ['dispatch-board'] as const,
  routeRuns: ['route-runs'] as const,
  routeRunDetail: (routeRunId: string) => ['route-run-detail', routeRunId] as const,
  routeRunStopTimeline: (stopId: string) => ['route-run-stop-timeline', stopId] as const,
  routeRunStopProofs: (stopId: string) => ['route-run-stop-proofs', stopId] as const,
  exceptions: ['exceptions'] as const,
  planner: (serviceDate: string) => ['planner', serviceDate] as const,
  routeVersions: (routeId: string) => ['route-versions', routeId] as const,
  rerouteHistory: (routeId: string) => ['reroute-history', routeId] as const,
};
